# Puppet Modules 
mod 'puppet-modules', :git => '/Users/malnick/projects/puppet-connect_solutions/puppet-modules/', :ref => 'mtlb_sso'

# Puppet Data
mod 'puppet-configuration', :git => '/Users/malnick/projects/puppet-connect_solutions/puppet-configuration/', :ref => 'mtlb_sso' 

# Aux Modules
