mod 'stdlib', :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'
mod 'apache', :git => 'https://github.com/puppetlabs/puppetlabs-apache'
mod 'mysql', :git => 'https://github.com/puppetlabs/puppetlabs-mysql'
